#!/usr/bin/env bash
# 统一部署入口（项目根目录为工作目录）
#   ./deploy/selfblog.sh release          # 等同原 server-release.sh（USE_HTTPS=1 等仍用环境变量）
#   ./deploy/selfblog.sh first-cert     # 首次 Let’s Encrypt
#   ./deploy/selfblog.sh renew-certs    # 续签 + nginx reload（供 crontab）
#   ./deploy/selfblog.sh nginx-gen bootstrap|ssl [0|1]   # 仅生成 Nginx 配置；末尾 1 表示 WITH_SITES
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

read_env_val() {
  local k="$1"
  grep -E "^${k}=" .env | tail -1 | sed "s/^${k}=//" | tr -d '\r' | sed 's/^"//;s/"$//;s/^'\''//;s/'\''$//'
}

append_compose_sites() {
  if [[ "$(read_env_val WITH_SITES)" != "1" ]]; then
    return 0
  fi
  local ah wh
  ah="$(read_env_val SITE_ADMIN_HOST)"
  wh="$(read_env_val SITE_WWW_HOST)"
  if [[ -z "${ah}" && -z "${wh}" ]]; then
    echo "WITH_SITES=1 时请在 .env 设置 SITE_ADMIN_HOST 和/或 SITE_WWW_HOST"
    return 1
  fi
  [[ -n "${ah}" ]] && COMPOSE+=(-f deploy/docker-compose.sites-admin.yml)
  [[ -n "${wh}" ]] && COMPOSE+=(-f deploy/docker-compose.sites-www.yml)
  return 0
}

# --- Nginx 配置生成（写入 deploy/nginx/generated/）---
nginx_generate() {
  local MODE="${1:-}"
  local WITH_SITES="${2:-0}"
  if [[ "${MODE}" != "bootstrap" && "${MODE}" != "ssl" ]]; then
    echo "用法: $0 nginx-gen <bootstrap|ssl> [0|1]"
    return 1
  fi
  if [[ ! -f .env ]]; then
    echo "缺少根目录 .env"
    return 1
  fi

  local API_HOST ADMIN_HOST WWW_HOST
  API_HOST="$(read_env_val LE_DOMAIN)"
  if [[ -z "${API_HOST}" ]]; then
    echo ".env 中 LE_DOMAIN 不能为空"
    return 1
  fi
  ADMIN_HOST=""
  WWW_HOST=""
  if [[ "${WITH_SITES}" == "1" ]]; then
    ADMIN_HOST="$(read_env_val SITE_ADMIN_HOST)"
    WWW_HOST="$(read_env_val SITE_WWW_HOST)"
    if [[ -z "${ADMIN_HOST}" && -z "${WWW_HOST}" ]]; then
      echo "WITH_SITES=1 时请在 .env 设置 SITE_ADMIN_HOST 和/或 SITE_WWW_HOST"
      return 1
    fi
  fi

  local OUT="${ROOT}/deploy/nginx/generated"
  mkdir -p "${OUT}"

  local proxy_api='        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;'

  if [[ "${MODE}" == "bootstrap" ]]; then
    {
      echo "# generated by deploy/selfblog.sh nginx-gen bootstrap"
      echo "server {"
      echo "    listen 80;"
      echo "    server_name ${API_HOST};"
      echo "    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }"
      echo "    location / {"
      echo "${proxy_api}"
      echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
      echo "    }"
      echo "}"
      if [[ -n "${ADMIN_HOST}" ]]; then
        echo "server {"
        echo "    listen 80;"
        echo "    server_name ${ADMIN_HOST};"
        echo "    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }"
        echo "    location / { return 204; }"
        echo "}"
      fi
      if [[ -n "${WWW_HOST}" ]]; then
        echo "server {"
        echo "    listen 80;"
        echo "    server_name ${WWW_HOST};"
        echo "    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }"
        echo "    location / { return 204; }"
        echo "}"
      fi
    } >"${OUT}/10-http.conf"
    rm -f "${OUT}/20-https.conf" "${OUT}/.ssl-ready"
    echo "==> Nginx 配置已写入 ${OUT}（bootstrap，仅 80 + ACME）"
  else
    {
      echo "# generated by deploy/selfblog.sh nginx-gen ssl"
      echo "server {"
      echo "    listen 80;"
      echo "    server_name ${API_HOST}${ADMIN_HOST:+ ${ADMIN_HOST}}${WWW_HOST:+ ${WWW_HOST}};"
      echo "    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }"
      echo "    location / { return 301 https://\$host\$request_uri; }"
      echo "}"
    } >"${OUT}/10-http.conf"
    local cert="/etc/letsencrypt/live/${API_HOST}/fullchain.pem"
    local key="/etc/letsencrypt/live/${API_HOST}/privkey.pem"
    {
      echo "# generated by deploy/selfblog.sh nginx-gen ssl"
      echo "server {"
      echo "    listen 443 ssl;"
      echo "    http2 on;"
      echo "    server_name ${API_HOST};"
      echo "    ssl_certificate ${cert};"
      echo "    ssl_certificate_key ${key};"
      echo "    location / {"
      echo "${proxy_api}"
      echo "        proxy_set_header X-Forwarded-Proto https;"
      echo "    }"
      echo "}"
      if [[ -n "${ADMIN_HOST}" ]]; then
        echo "server {"
        echo "    listen 443 ssl;"
        echo "    http2 on;"
        echo "    server_name ${ADMIN_HOST};"
        echo "    ssl_certificate ${cert};"
        echo "    ssl_certificate_key ${key};"
        echo "    location / {"
        echo "        proxy_pass http://admin-site:80;"
        echo "        proxy_http_version 1.1;"
        echo "        proxy_set_header Host \$host;"
        echo "        proxy_set_header X-Real-IP \$remote_addr;"
        echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
        echo "        proxy_set_header X-Forwarded-Proto https;"
        echo "    }"
        echo "}"
      fi
      if [[ -n "${WWW_HOST}" ]]; then
        echo "server {"
        echo "    listen 443 ssl;"
        echo "    http2 on;"
        echo "    server_name ${WWW_HOST};"
        echo "    ssl_certificate ${cert};"
        echo "    ssl_certificate_key ${key};"
        echo "    location / {"
        echo "        proxy_pass http://web:3000;"
        echo "        proxy_http_version 1.1;"
        echo "        proxy_set_header Host \$host;"
        echo "        proxy_set_header X-Real-IP \$remote_addr;"
        echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
        echo "        proxy_set_header X-Forwarded-Proto https;"
        echo "    }"
        echo "}"
      fi
    } >"${OUT}/20-https.conf"
    touch "${OUT}/.ssl-ready"
    echo "==> Nginx 配置已写入 ${OUT}（ssl，80 跳转 + 443）"
  fi
}

cmd_release() {
  if [[ -f .env ]]; then
    if [[ "$(read_env_val WITH_SITES)" == "1" ]] && [[ "${USE_HTTPS:-}" != "1" ]]; then
      echo "WITH_SITES=1 仅在与 Nginx+HTTPS 同机部署时有效，请使用: USE_HTTPS=1 ./deploy/selfblog.sh release"
      exit 1
    fi
  else
    echo "缺少根目录 .env。请: cp deploy/.env.production.example .env && 编辑"
    exit 1
  fi

  COMPOSE=(docker compose -f docker-compose.yml -f deploy/docker-compose.cloud.yml)
  if [[ "${USE_HTTPS:-}" == "1" ]]; then
    COMPOSE+=(-f deploy/docker-compose.https.yml)
  fi
  COMPOSE+=(--env-file .env)

  if [[ "${USE_HTTPS:-}" == "1" ]]; then
    append_compose_sites || exit 1
  fi

  if [[ "${USE_HTTPS:-}" == "1" ]]; then
    _le_domain="$(read_env_val LE_DOMAIN)"
    _le_email="$(read_env_val LE_EMAIL)"
    if [[ -z "${_le_domain}" ]] || [[ -z "${_le_email}" ]]; then
      echo "USE_HTTPS=1 时 .env 必须包含 LE_DOMAIN= 与 LE_EMAIL="
      exit 1
    fi
    SITES_FLAG=0
    [[ "$(read_env_val WITH_SITES)" == "1" ]] && SITES_FLAG=1
    if [[ -f deploy/nginx/generated/.ssl-ready ]]; then
      echo "==> 生成 Nginx 配置（HTTPS）"
      nginx_generate ssl "${SITES_FLAG}"
    else
      echo "==> 生成 Nginx 引导配置（仅 80；证书请执行 ./deploy/selfblog.sh first-cert）"
      nginx_generate bootstrap "${SITES_FLAG}"
    fi
  fi

  echo "==> 构建并启动 selfblog（postgres 不映射宿主机端口）"
  if [[ "${USE_HTTPS:-}" == "1" ]]; then
    echo "    （USE_HTTPS=1：Nginx 80/443；首次证书: ./deploy/selfblog.sh first-cert）"
    [[ "$(read_env_val WITH_SITES)" == "1" ]] && echo "    （WITH_SITES=1：同机反代 admin / www）"
  fi
  "${COMPOSE[@]}" up -d --build

  echo "==> 状态（-a 含已退出的 api 容器）"
  "${COMPOSE[@]}" ps -a

  echo ""
  if [[ "${USE_HTTPS:-}" == "1" ]]; then
    echo "本机经 Nginx 自检: curl -sS http://127.0.0.1/health   （若已 first-cert 则用 https）"
  else
    echo "本机自检 API: curl -sS http://127.0.0.1:8080/health"
  fi
  echo ""

  if [[ "${PRUNE_UNUSED_IMAGES:-}" == "1" ]]; then
    echo "==> PRUNE_UNUSED_IMAGES=1：删除未被任何容器使用的镜像"
    docker image prune -a -f
  fi
  if [[ "${PRUNE_EVERYTHING_UNUSED:-}" == "1" ]]; then
    echo "==> PRUNE_EVERYTHING_UNUSED=1：docker system prune -a -f"
    docker system prune -a -f
  fi
  echo ""
  echo "若仍想清理构建缓存: docker builder prune -f"
  echo "危险（会删未使用卷）: docker system prune -a -f --volumes"
}

cmd_first_cert() {
  if [[ ! -f .env ]]; then
    echo "缺少 .env"
    exit 1
  fi
  local LE_DOMAIN LE_EMAIL
  LE_DOMAIN="$(read_env_val LE_DOMAIN)"
  LE_EMAIL="$(read_env_val LE_EMAIL)"
  if [[ -z "${LE_DOMAIN}" ]] || [[ -z "${LE_EMAIL}" ]]; then
    echo "请在 .env 中设置 LE_DOMAIN 与 LE_EMAIL"
    exit 1
  fi

  local SITES_FLAG=0
  [[ "$(read_env_val WITH_SITES)" == "1" ]] && SITES_FLAG=1

  COMPOSE=(
    docker compose
    -f docker-compose.yml
    -f deploy/docker-compose.cloud.yml
    -f deploy/docker-compose.https.yml
    --env-file .env
  )
  append_compose_sites || exit 1

  if [[ ! -f deploy/nginx/generated/.ssl-ready ]]; then
    echo "==> 生成 Nginx 引导配置（仅 80 + ACME）"
    nginx_generate bootstrap "${SITES_FLAG}"
  fi

  echo "==> 确保栈已启动"
  "${COMPOSE[@]}" up -d --build

  local CERTBOT_D=(-d "${LE_DOMAIN}")
  if [[ "${SITES_FLAG}" == "1" ]]; then
    local _admin _www
    _admin="$(read_env_val SITE_ADMIN_HOST)"
    _www="$(read_env_val SITE_WWW_HOST)"
    [[ -n "${_admin}" ]] && CERTBOT_D+=(-d "${_admin}")
    [[ -n "${_www}" ]] && CERTBOT_D+=(-d "${_www}")
  fi

  echo "==> 申请证书（webroot）"
  COMPOSE_PROFILES=cert "${COMPOSE[@]}" run --rm certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    "${CERTBOT_D[@]}" \
    --email "${LE_EMAIL}" \
    --agree-tos \
    --no-eff-email

  echo "==> 切换为 HTTPS + HTTP 跳转"
  nginx_generate ssl "${SITES_FLAG}"

  "${COMPOSE[@]}" restart nginx

  echo "==> 完成。请用 https://${LE_DOMAIN}/health 自测，PUBLIC_URL / CORS_ORIGINS 改为 https。"
}

cmd_renew_certs() {
  if [[ ! -f .env ]]; then
    exit 0
  fi
  COMPOSE=(
    docker compose
    -f docker-compose.yml
    -f deploy/docker-compose.cloud.yml
    -f deploy/docker-compose.https.yml
    --env-file .env
  )
  append_compose_sites || exit 1
  COMPOSE_PROFILES=cert "${COMPOSE[@]}" run --rm certbot renew --webroot -w /var/www/certbot --quiet
  "${COMPOSE[@]}" exec nginx nginx -s reload
}

cmd_help() {
  cat <<'EOF'
用法（均在项目根目录下，通过本脚本自动 cd）：

  ./deploy/selfblog.sh release
      构建并启动栈。环境变量与原先一致：
      USE_HTTPS=1、PRUNE_*、等。

  ./deploy/selfblog.sh first-cert
      首次 Let’s Encrypt（须已 release 且 80 可达）。

  ./deploy/selfblog.sh renew-certs
      续签证书并 nginx reload（适合 crontab）。

  ./deploy/selfblog.sh nginx-gen bootstrap|ssl [0|1]
      仅重写 deploy/nginx/generated/；可选 1 表示按 WITH_SITES 生成多站点。

兼容：./deploy/server-release.sh、first-cert.sh、renew-certs.sh、nginx/generate.sh
      仍为指向本脚本的薄包装，可继续照旧路径调用。
EOF
}

main() {
  local cmd="${1:-help}"
  case "${cmd}" in
    release) cmd_release ;;
    first-cert) cmd_first_cert ;;
    renew-certs) cmd_renew_certs ;;
    nginx-gen)
      shift
      nginx_generate "${1:-}" "${2:-0}" || exit 1
      ;;
    help | --help | -h) cmd_help ;;
    *)
      echo "未知子命令: ${cmd}"
      cmd_help
      exit 1
      ;;
  esac
}

main "$@"
